### ISSUE TITLE
loadable-component not found

### ISSUE THREAD

**Issue by milky2028** [dan-harris/ngx-loadable-component#18]
Hello! Thanks for making this. I'm not sure if I missed a step or what, but I keep getting an error where Angular can't find the loadable component. "loadable-component is not a known element"

Any help is much appreciated.

**Comment by dan-harris** [comment]
Hey @milky2028 - thanks for giving it a shot 🎉

Have you tried importing the `LoadableComponentModule.forFeature()` within your module imports?
e.g. 
```js
import { LoadableComponentModule } from 'ngx-loadable-component';

@NgModule({
  declarations: [
      ...
  ],
  imports: [
    ...
    LoadableComponentModule.forFeature()
  ]
})
export class MyFeatureModule { }
```

If that doesnt work, i'll try put together a stackblitz with it working 👍

**Comment by milky2028** [comment]
Thanks for getting back to me! I'll try this today and see if I can get it working.

**Comment by milky2028** [comment]
Yeah, I still can't seem to get it to work :sob: . A Stackblitz example might help, but if you publish your demo source code, I might also be able to figure it out from there. Thanks!

**Comment by dan-harris** [comment]
Right, so this is my fault as it's an omission from the readme. You need to currently have your build setup to use `aot`. An example of my test app &  demo is actually within this repo (it's the base 'app', with the library actually sitting in the `projects` directory). Apologies for the run around 😊.

The example angular.json setup for your dev build is below (just put the `aot: true` part in);

https://github.com/dan-harris/ngx-loadable-component/blob/655c922b82c3488d4eb92ba2baf44af1d40982f5/angular.json#L51-L56

**Comment by dan-harris** [comment]
Updated readme as a quick solution... will look into non-aot dev builds as a backlog item.

**Comment by milky2028** [comment]
Thanks! This is almost certainly my issue, I've been trying to serve in dev mode with a non-aot build.
